version: 1.0.{build}
image: Visual Studio 2017

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "6"
  ATHENA_DATA_TESTS_CON: Server=localhost;User ID=postgres;Password=Password12!;Database=postgres

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version

services: postgresql96

cache:
 - 'src\Athena\node_modules'
 - '%USERPROFILE%\.nuget\packages'

build_script:
- ps: ./build.ps1 -t CodeCov::Publish

# We run tests in our build. Appveyor shouldn't try to discover them
test: off
